[CmdletBinding()]
param(
    [string]$Root = $(if ($env:GITHUB_WORKSPACE) { $env:GITHUB_WORKSPACE } else { (Get-Location).Path }),
    [string]$Configuration = "Release",
    [string]$Platform = "x64",
    [string]$PackageName = "kainote-windows-x64"
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path -LiteralPath $Root).Path
$DistDir = Join-Path $Root "dist"
$StageDir = Join-Path $DistDir $PackageName
$Archive = Join-Path $DistDir "$PackageName.zip"

if (Test-Path -LiteralPath $StageDir) { Remove-Item -LiteralPath $StageDir -Recurse -Force }
if (Test-Path -LiteralPath $Archive) { Remove-Item -LiteralPath $Archive -Force }
New-Item -ItemType Directory -Force -Path $StageDir, $DistDir | Out-Null

$outputCandidates = @(
    (Join-Path $Root "$Platform\$Configuration"),
    (Join-Path $Root "bin\$Platform\$Configuration"),
    (Join-Path $Root "Kainote\$Platform\$Configuration"),
    (Join-Path $Root "Kainote\bin\$Platform\$Configuration")
) | Select-Object -Unique

$existingOutputs = @($outputCandidates | Where-Object { Test-Path -LiteralPath $_ })
if ($existingOutputs.Count -eq 0) {
    throw "No Windows build output directories found. Checked: $($outputCandidates -join ', ')"
}

$executable = $null
foreach ($dir in $existingOutputs) {
    $executable = Get-ChildItem -LiteralPath $dir -Recurse -File -Include "KaiNote.exe", "Kainote.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($executable) { break }
}
if (-not $executable) {
    throw "No KaiNote.exe/Kainote.exe found under: $($existingOutputs -join ', ')"
}

foreach ($dir in $existingOutputs) {
    Write-Host "Copying build output: $dir"
    Copy-Item -Path (Join-Path $dir "*") -Destination $StageDir -Recurse -Force
}

# Copy source-tree runtime resources when they are not already generated by the
# Visual Studio projects. Missing optional directories are ignored because not all
# repository checkouts include the same release-only payloads.
foreach ($dirName in @("Automation", "Dictionary", "Locale", "Themes", "Csri")) {
    $sourceDir = Join-Path $Root $dirName
    $destDir = Join-Path $StageDir $dirName
    if ((Test-Path -LiteralPath $sourceDir) -and -not (Test-Path -LiteralPath $destDir)) {
        Write-Host "Copying runtime resource directory: $dirName"
        Copy-Item -LiteralPath $sourceDir -Destination $destDir -Recurse -Force
    }
}

foreach ($fileName in @("README.md", "LICENSE", "LICENSE.txt")) {
    $sourceFile = Join-Path $Root $fileName
    if (Test-Path -LiteralPath $sourceFile) {
        Copy-Item -LiteralPath $sourceFile -Destination $StageDir -Force
    }
}

# The app links to the VC runtime and legacy D3DX9 runtime. Include them if the
# runner exposes the DLLs, matching the existing upstream zip layout.
foreach ($dllName in @("msvcp140.dll", "vcruntime140.dll", "vcruntime140_1.dll", "concrt140.dll", "D3DX9_43.dll")) {
    if (Test-Path -LiteralPath (Join-Path $StageDir $dllName)) { continue }
    foreach ($systemDir in @((Join-Path $env:WINDIR "System32"), (Join-Path $env:WINDIR "SysWOW64"))) {
        $candidate = Join-Path $systemDir $dllName
        if (Test-Path -LiteralPath $candidate) {
            Copy-Item -LiteralPath $candidate -Destination $StageDir -Force
            break
        }
    }
}

# CSRI renderers are loaded from a Csri/ directory by Kainote. If the VSFilter
# project produced a DLL outside the main output folder, include it there too.
$csriDir = Join-Path $StageDir "Csri"
New-Item -ItemType Directory -Force -Path $csriDir | Out-Null
$rendererRoots = @(
    (Join-Path $Root "Thirdparty\xy-VSFilter-xy_sub_filter_rc5"),
    (Join-Path $Root "Thirdparty\karahelper"),
    (Join-Path $Root "bin\$Platform\$Configuration")
) | Where-Object { Test-Path -LiteralPath $_ }
foreach ($rendererRoot in $rendererRoots) {
    Get-ChildItem -LiteralPath $rendererRoot -Recurse -File -Include "VSFilter*.dll", "xy-VSFilter*.dll", "karahelper.dll" -ErrorAction SilentlyContinue |
        ForEach-Object {
            Copy-Item -LiteralPath $_.FullName -Destination $csriDir -Force
        }
}

$manifestPath = Join-Path $StageDir "artifact-manifest.txt"
Get-ChildItem -LiteralPath $StageDir -Recurse -File |
    Sort-Object FullName |
    ForEach-Object {
        $relative = $_.FullName.Substring($StageDir.Length).TrimStart('\', '/')
        "{0}`t{1}" -f $relative, $_.Length
    } | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Compress-Archive -Path (Join-Path $StageDir "*") -DestinationPath $Archive -CompressionLevel Optimal
$archiveInfo = Get-Item -LiteralPath $Archive
Write-Host ("Created {0} ({1} bytes)" -f $archiveInfo.FullName, $archiveInfo.Length)

if ($env:GITHUB_OUTPUT) {
    "archive=$Archive" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
    "package_name=$PackageName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
}
